apply plugin: 'com.android.library'
def unityStreamingAssets = ""//手動新增定義

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    //implementation(name: 'arcore_client', ext:'aar')//重複的依賴
    implementation(name: 'UnityARCore', ext:'aar')
    implementation(name: 'ARPresto', ext:'aar')
    implementation(name: 'nativebindings', ext:'aar')
    implementation(name: 'poseplugin', ext:'aar')
    implementation(name: 'unityandroidpermissions', ext:'aar')//重複的依賴
    implementation project(':UnityLibrary:xrmanifest.androidlib') //手動更改

}

android {
    namespace "com.unity3d.player"
    ndkPath "C:/Program Files/Unity/Hub/Editor/2022.3.60f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK"
    ndkVersion "23.1.7779620"
    compileSdkVersion 35
    buildToolsVersion '35.0.0' //要手動更改符合的版本35，原本為34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17 //手動更改和android studio版本相同java 17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 34
        //增加匹配版本
        ndk {
            abiFilters 'arm64-v8a'
        }
        versionCode 1
        versionName '0.1'
        consumerProguardFiles 'proguard-unity.txt'
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = ['.unity3d', '.ress', '.resource', '.obb', '.bundle', '.unityexp'] + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }

    packagingOptions {
        doNotStrip '*/arm64-v8a/*.so'
        jniLibs {
            useLegacyPackaging true
        }
    }
}

def getSdkDir() {
    Properties local = new Properties()
    local.load(new FileInputStream("${rootDir}/local.properties"))
    return local.getProperty('sdk.dir')
}

def BuildIl2Cpp(String workingDir, String configuration, String architecture, String abi, String[] staticLibraries) {
    def commandLineArgs = []
    commandLineArgs.add("--compile-cpp")
    commandLineArgs.add("--platform=Android")
    commandLineArgs.add("--architecture=" + architecture)
    commandLineArgs.add("--outputpath=" + workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.so")
    commandLineArgs.add("--baselib-directory=" + workingDir + "/src/main/jniStaticLibs/" + abi)
    commandLineArgs.add("--incremental-g-c-time-slice=3")
    commandLineArgs.add("--configuration=" + configuration)
    commandLineArgs.add("--dotnetprofile=unityaot-linux")
    commandLineArgs.add("--profiler-report")
    commandLineArgs.add("--profiler-output-file=" + workingDir + "/build/il2cpp_"+ abi + "_" + configuration + "/il2cpp_conv.traceevents")
    commandLineArgs.add("--print-command-line")
    commandLineArgs.add("--data-folder=" + workingDir + "/src/main/Il2CppOutputProject/Source/il2cppOutput/data")
    commandLineArgs.add("--generatedcppdir=" + workingDir + "/src/main/Il2CppOutputProject/Source/il2cppOutput")
    commandLineArgs.add("--cachedirectory=" + workingDir + "/build/il2cpp_"+ abi + "_" + configuration + "/il2cpp_cache")
    commandLineArgs.add("--tool-chain-path=" + android.ndkDirectory)
    staticLibraries.eachWithIndex {fileName, i->
        commandLineArgs.add("--additional-libraries=" + workingDir + "/src/main/jniStaticLibs/" + abi + "/" + fileName)
    }
    def executableExtension = ""
    if (org.gradle.internal.os.OperatingSystem.current().isWindows()) {
        executableExtension = ".exe"
        commandLineArgs = commandLineArgs*.replace('\"', '\\\"')
    }
    exec {
        executable workingDir + "/src/main/Il2CppOutputProject/IL2CPP/build/deploy/il2cpp" + executableExtension
        args commandLineArgs
        environment "ANDROID_SDK_ROOT", getSdkDir()
    }
    delete workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.sym.so"
    ant.move(file: workingDir + "/src/main/jniLibs/" + abi + "/libil2cpp.dbg.so", tofile: workingDir + "/symbols/" + abi + "/libil2cpp.so")
}

android {
    //增加兩個匹配資料
    task BuildIl2CppTask {
        doLast {
            BuildIl2Cpp(projectDir.toString().replaceAll('\\\\', '/'), 'Release', 'arm64', 'arm64-v8a', [  ] as String[])
        }
    }
    /*
    afterEvaluate {
        if (project(':UnityLibrary').tasks.findByName('mergeDebugJniLibFolders'))
            project(':UnityLibrary').mergeDebugJniLibFolders.dependsOn BuildIl2CppTask
        if (project(':UnityLibrary').tasks.findByName('mergeReleaseJniLibFolders'))
            project(':UnityLibrary').mergeReleaseJniLibFolders.dependsOn BuildIl2CppTask
    }

     */
    //替換寫法
    afterEvaluate {
        if (tasks.findByName('mergeDebugJniLibFolders')) {
            tasks.named('mergeDebugJniLibFolders').configure { it.dependsOn(BuildIl2CppTask) }
        }
        if (tasks.findByName('mergeReleaseJniLibFolders')) {
            tasks.named('mergeReleaseJniLibFolders').configure { it.dependsOn(BuildIl2CppTask) }
        }
    }
    sourceSets {
        main {
            jni.srcDirs = ["src/main/Il2CppOutputProject"]
        }
    }
}



