plugins {
    alias(libs.plugins.android.application)
    id 'com.chaquo.python'
}

android {
    namespace 'com.example.cameraproject_2'
    compileSdk 35

    defaultConfig {
        applicationId "com.example.cameraproject_2"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
        packagingOptions {
            jniLibs {
                useLegacyPackaging true
            }
        }

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        //使用python

        ndk {
            abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
        }

        python {
            version "3.11"
        }

        python {
            buildPython "C:/Users/User/.conda/envs/py311/python.exe"
        }



        sourceSets {
            main {
                python.srcDir "src/main/python"
            }
        }



    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17 //原本使用版本11//之前需要使用改成17
        targetCompatibility JavaVersion.VERSION_17

    }

    //除錯用
    packagingOptions {
        pickFirst 'lib/x86_64/libc++_shared.so'
        jniLibs {
            useLegacyPackaging true
        }
    }
    sourceSets {
        main {
            jni {
                srcDirs 'src\\main\\jni', 'src\\main\\res\\xml\\file_paths'
            }
        }
    }
    //強制使用單一版本
    configurations.all {
        resolutionStrategy {
            force 'com.google.ar.sceneform:core:1.17.1'
            force 'com.google.ar.sceneform:sceneform-base:1.17.1'
        }
    }
    ndkVersion '23.1.7779620'
}

dependencies {

    implementation libs.appcompat
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout


    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core


    implementation project(':sdk')//opencv
    implementation project(':UnityLibrary')//unity
    implementation 'com.github.bumptech.glide:glide:4.16.0'
    annotationProcessor 'com.github.bumptech.glide:compiler:4.16.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'

    //製作ar core需要的
    //implementation 'com.google.ar:core:1.39.0'
    implementation 'com.google.ar.sceneform:core:1.17.1'
    implementation 'com.google.ar.sceneform:assets:1.17.1'
    //implementation 'com.google.ar.sceneform.ux:sceneform-ux:1.17.1'
    //implementation 'dev.romainguy.sceneview:sceneview:1.x.x'

    //implementation 'com.google.ar.sceneform:core:1.18.0'
    //implementation 'com.google.ar.sceneform.ux:sceneform-ux:1.18.0'
    //implementation 'com.google.ar:core:1.34.0'


    //無金鑰授權
    implementation 'com.google.android.gms:play-services-auth:16+'

    //製作google map地圖需要的
    implementation 'com.google.android.gms:play-services-maps:18.0.2'
    implementation 'com.squareup.okhttp3:okhttp:4.10.0'

//以下為API使用區塊!!!!!!!
    // AndroidX
    implementation "androidx.appcompat:appcompat:1.6.1" // 請檢查最新版本
    implementation "com.google.android.material:material:1.9.0" // 請檢查最新版本
    implementation "androidx.constraintlayout:constraintlayout:2.1.4" // 請檢查最新版本

    // Retrofit for network requests
    implementation "com.squareup.retrofit2:retrofit:2.9.0"
    implementation "com.squareup.retrofit2:converter-gson:2.9.0" // 用於 JSON 解析
    implementation "com.squareup.okhttp3:okhttp:4.10.0"
    implementation "com.squareup.okhttp3:logging-interceptor:4.10.0" // 可選，網路日誌

    // Room
    def room_version = "2.6.1" // 使用最新的穩定版本
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    // Kotlin Extensions and Coroutines support for Room
    implementation "androidx.room:room-ktx:$room_version"
    // Test helpers
    testImplementation "androidx.room:room-testing:$room_version"


    // ViewModel and LiveData
    implementation "androidx.lifecycle:lifecycle-viewmodel:2.6.2" // 請檢查最新版本
    implementation "androidx.lifecycle:lifecycle-livedata:2.6.2"
    implementation "androidx.activity:activity:1.8.0" // For by viewModels() if you were using Kotlin, but for Java use ViewModelProvider
}

//api-test分支新增的 但感覺用不到 先標註起來
    // 使用 View Binding
    /*android {
        // ...
        buildFeatures {
            viewBinding true
        }*/

    //unity需要
    implementation 'com.google.ar:core:1.44.0'


    //資料庫權限
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'


    //動畫(?)
    implementation 'com.airbnb.android:lottie:3.4.1'

    //群組需要使用
    implementation 'org.json:json:20230227'

    //訊息框UI
    implementation 'androidx.cardview:cardview:1.0.0'

    // 用於載入頭像
    implementation 'com.squareup.picasso:picasso:2.71828'

    //圓點顯示
    implementation 'androidx.viewpager2:viewpager2:1.0.0'
    implementation 'com.google.android.material:material:1.9.0'
        

}